# Generated by Django 5.1.1 on 2024-11-25 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinquedo', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('passo_a_passo', models.TextField()),
                ('imagem', models.ImageField(blank=True, default='boneca.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('contato', models.EmailField(max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('descricao', models.TextField(blank=True, max_length=100)),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
                ('date_added', models.DateTimeField(null=True)),
                ('date_exit', models.DateTimeField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, default='logo_do_instoky.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='material_de_um_brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('brinquedo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brinquedo', to='estoque.brinquedo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('descricao', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluido', 'Concluído')], default='Pendente', max_length=20)),
                ('data_de_entrega', models.DateField(blank=True, null=True)),
                ('brinquedo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brinquedo_de_um_pedido', to='estoque.brinquedo')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='estoque.cliente')),
            ],
        ),
    ]
