# Generated by Django 5.1.1 on 2024-11-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('data_de_escrita', models.DateField(auto_now_add=True)),
                ('estrelas', models.IntegerField(blank=True, null=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='estoque.pedido')),
            ],
        ),
    ]
