# Generated by Django 5.1.1 on 2024-11-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_de_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
