# Generated by Django 5.1.1 on 2024-11-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_pedido_data_de_solicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_de_Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=12, null=True)),
                ('quantidade', models.IntegerField()),
                ('data_de_saida', models.DateField(auto_now_add=True)),
                ('razao', models.TextField(blank=True, max_length=200, null=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_saida_chegada', to='estoque.material')),
            ],
        ),
    ]
