# Generated by Django 5.1.1 on 2024-11-27 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_registro_de_transacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_de_transacoes',
            name='brinquedo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brinquedo_saida_chegada', to='estoque.brinquedo'),
        ),
        migrations.AddField(
            model_name='registro_de_transacoes',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_saida_chegada', to='estoque.pedido'),
        ),
    ]
