# Generated by Django 5.1.1 on 2024-11-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_registro_de_transacoes_brinquedo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
