# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - djangodeploy

on:
  push:
    branches:
      - prod2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd projeto_django
          pip install -r requirements.txt
          npm install cypress --save -include=dev
          npm ci
          cd ..

      - name: Run local server
        run: |
          cd projeto_django
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run
          cd ..

      - name: Cleaning testing files
        run: |
          cd projeto_django/
          rm db.sqlite3
          cd ..
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          cd projeto_django/
          zip release.zip ./* -r
          cd ..
          mv projeto_django/release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D11A5F56D9B4A1A9AA0E66A24AF60AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC0066C2C7D6430CA95037E464E448B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E6F397187F84BFABE92B35CF8C3C82D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'djangodeploy'
          slot-name: 'Production'
          
